'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let page='solutions',filtered=[],listPage=0,current=null,puzzle=null,battle=null,record=null,epoch=0,puzzleEpoch=0,engineReady=false,sgfURL=null,demoTimer=null;
const ANALYSIS_VISIT_OPTIONS=[64,96,256,512,800,1200];let ANALYSIS_VISITS=800;try{const saved=Number(localStorage.getItem('yijing.analysisVisits.v1'));if(ANALYSIS_VISIT_OPTIONS.includes(saved))ANALYSIS_VISITS=saved;}catch{}
const allPuzzles=[...(window.SOLUTION_PUZZLES||[])];
const AI_LEVELS={beginner:{name:'新手',profile:'rank_20k',visits:1,temperature:1.35,hint:'入门 · 人类 20 级 · 1 次访问，最宽的落子分布'},human10k:{name:'入门',profile:'rank_10k',visits:2,temperature:1.22,hint:'入门 · 人类10级 · 2 次访问，保留明显的人类落子倾向'},veteran:{name:'老手',profile:'rank_5k',visits:4,temperature:1.05,hint:'老手 · 人类 5 级 · 4 次访问，稳健但仍会犯错'},amateur:{name:'业余高手',profile:'rank_1d',visits:16,temperature:.76,hint:'业余高手 · 人类 1 段 · 16 次访问，业余强手棋风'},amateur5d:{name:'业余顶尖',profile:'rank_5d',visits:32,temperature:.62,hint:'业余顶尖 · 人类5段 · 32 次访问，接近高段业余棋力'},pro:{name:'职业棋手',profile:'rank_9d',visits:64,temperature:.48,hint:'职业棋手 · 职业九段 · 64 次访问，接近职业的选择'},ai:{name:'AI',profile:null,visits:256,temperature:0,hint:'KataGo · 256 次访问，每次选择一选'}};
const DEFAULT_BATTLE_CONFIG={n:19,aiLevel:'amateur',aiVisits:256,aiTemperature:0,aiPVLen:12,resignAfter:150,resignThreshold:1,resignStreak:12};
const audio={enabled:true,bgmEnabled:true,mode:'rain',volume:.55,ctx:null,master:null,bgmTimer:null,bgmStep:0};
const BOARD_THEMES={bamboo:{base:'#e6c796',edge:'#f3ddb1',line:'#806a47',star:'#705837'},walnut:{base:'#ae7a4b',edge:'#d19b64',line:'#5b3826',star:'#4a2a1b'},paper:{base:'#e9e0c8',edge:'#f8f2df',line:'#8a7c61',star:'#665947'},lacquer:{base:'#8b5638',edge:'#d19a61',line:'#4c2c24',star:'#3c211c',texture:'grain'},slate:{base:'#727c78',edge:'#b2b6a8',line:'#3f4b48',star:'#35403d',texture:'slate'}};
const STONE_THEMES={classic:{blackA:'#454844',blackB:'#20231f',blackLine:'#1d201c',whiteA:'#ffffff',whiteB:'#e4e3d9',whiteLine:'#b8b8a9'},jade:{blackA:'#3e5d52',blackB:'#152c25',blackLine:'#10221c',whiteA:'#e9f0df',whiteB:'#bdcbb8',whiteLine:'#9aa995'},ink:{blackA:'#37322e',blackB:'#0c0c0b',blackLine:'#050505',whiteA:'#fbf2df',whiteB:'#d8c7ad',whiteLine:'#bcaa90'},amber:{blackA:'#56443a',blackB:'#1d120e',blackLine:'#120a07',whiteA:'#fff4d7',whiteB:'#d8b36f',whiteLine:'#9c713d'},porcelain:{blackA:'#50545a',blackB:'#11151b',blackLine:'#090c10',whiteA:'#fffefa',whiteB:'#d5e2e8',whiteLine:'#91a4ad'}};
const appearance={board:'bamboo',stones:'classic'};try{Object.assign(appearance,JSON.parse(localStorage.getItem('yijing.appearance.v1')||'{}'));}catch{}
let studied;try{studied=new Set(JSON.parse(localStorage.getItem('yijing.studied.v2')||'[]'));}catch{studied=new Set();}

function game(n,stones=[],player='B'){const board=Go.empty(n);for(const [c,x,y] of stones)board[y][x]=c;return {n,board,initial:stones,initialPlayer:player,turn:player,moves:[],snapshots:[],keys:[Go.key(board)],captures:{B:0,W:0},last:null,busy:false,phase:'play',dead:new Set(),recommendations:[],evalBlack:null,evalScore:null,aiPoorStreak:0,resignText:'',insightVisible:false,started:false,config:{...DEFAULT_BATTLE_CONFIG,n}};}
function stopBgm(){if(audio.bgmTimer)clearInterval(audio.bgmTimer);audio.bgmTimer=null;}
function ensureAudio(){if(!audio.enabled)return;if(!audio.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;audio.ctx=new C();audio.master=audio.ctx.createGain();audio.master.gain.value=audio.volume;audio.master.connect(audio.ctx.destination);}if(audio.ctx.state==='suspended')audio.ctx.resume();if(audio.mode!=='none'&&!audio.bgmTimer){audio.bgmEnabled=true;ambientNote();audio.bgmTimer=setInterval(ambientNote,4200);}}
function tone(freq,duration,gain,type='sine'){if(!audio.ctx||!audio.master||!audio.enabled)return;const now=audio.ctx.currentTime,osc=audio.ctx.createOscillator(),amp=audio.ctx.createGain();osc.type=type;osc.frequency.value=freq;amp.gain.setValueAtTime(0,now);amp.gain.linearRampToValueAtTime(gain,now+.04);amp.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(amp);amp.connect(audio.master);osc.start(now);osc.stop(now+duration+.05);}
function noiseTexture(duration,gain,frequency,q=.5){if(!audio.ctx||!audio.master||!audio.enabled||!audio.bgmEnabled)return;const ctx=audio.ctx,now=ctx.currentTime,samples=Math.floor(ctx.sampleRate*duration),buffer=ctx.createBuffer(1,samples,ctx.sampleRate),data=buffer.getChannelData(0);let brown=0;for(let i=0;i<samples;i++){brown=(brown+.03*(Math.random()*2-1))*.99;data[i]=brown*3;}const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),amp=ctx.createGain();src.buffer=buffer;filter.type='lowpass';filter.frequency.value=frequency;filter.Q.value=q;amp.gain.setValueAtTime(.0001,now);amp.gain.linearRampToValueAtTime(gain,now+.35);amp.gain.linearRampToValueAtTime(gain*.72,now+duration*.7);amp.gain.exponentialRampToValueAtTime(.0001,now+duration);src.connect(filter);filter.connect(amp);amp.connect(audio.master);src.start(now);src.stop(now+duration+.05);}
function ambientNote(){if(!audio.ctx||!audio.enabled||!audio.bgmEnabled||audio.mode==='none')return;const step=audio.bgmStep++;if(audio.mode==='wind'){noiseTexture(4.35,.085,720,.75);tone([98,110,123,110][step%4],3.8,.018,'sine');return;}if(audio.mode==='stream'){noiseTexture(4.35,.07,1550,.5);tone([146.83,164.81,196,220,246.94][step%5],2.8,.012,'sine');for(let i=0;i<2;i++)setTimeout(()=>tone(880+Math.random()*420,.07,.012,'sine'),300+Math.random()*2500);return;}if(audio.mode==='guqin'){noiseTexture(4.35,.018,600,.35);tone([146.83,164.81,196,220,246.94,293.66][step%6],2.7,.035,'triangle');setTimeout(()=>tone([293.66,329.63,392][step%3],1.1,.012,'sine'),700);return;}if(audio.mode==='bamboo'){noiseTexture(4.35,.065,420,.8);tone([110,123.47,146.83,164.81][step%4],3.2,.014,'sine');for(let i=0;i<2;i++)setTimeout(()=>tone(520+Math.random()*260,.05,.011,'sine'),500+Math.random()*2300);return;}noiseTexture(4.35,.055,2500,.45);const notes=[196,220,261.63,293.66,329.63,392,329.63,261.63];tone(notes[step%notes.length],3.4,.014,'sine');for(let i=0;i<3;i++)setTimeout(()=>tone(720+Math.random()*700,.08,.018,'sine'),180+Math.random()*2600);}
function woodStrike(capture=false){if(!audio.ctx||!audio.master||!audio.enabled)return;const ctx=audio.ctx,now=ctx.currentTime,body=ctx.createOscillator(),bodyAmp=ctx.createGain(),filter=ctx.createBiquadFilter(),noise=ctx.createBufferSource(),noiseAmp=ctx.createGain(),buffer=ctx.createBuffer(1,Math.floor(ctx.sampleRate*.055),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);body.type='triangle';body.frequency.setValueAtTime(capture?118:172,now);body.frequency.exponentialRampToValueAtTime(capture?72:108,now+.19);bodyAmp.gain.setValueAtTime(.0001,now);bodyAmp.gain.exponentialRampToValueAtTime(capture?.22:.16,now+.006);bodyAmp.gain.exponentialRampToValueAtTime(.0001,now+.24);body.connect(bodyAmp);bodyAmp.connect(audio.master);filter.type='bandpass';filter.frequency.value=capture?1050:1450;filter.Q.value=.7;noise.buffer=buffer;noise.connect(filter);noiseAmp.gain.setValueAtTime(capture?.16:.12,now);noiseAmp.gain.exponentialRampToValueAtTime(.0001,now+.055);filter.connect(noiseAmp);noiseAmp.connect(audio.master);body.start(now);body.stop(now+.27);noise.start(now);noise.stop(now+.06);if(capture){const ring=ctx.createOscillator(),ringAmp=ctx.createGain();ring.type='sine';ring.frequency.value=310;ringAmp.gain.setValueAtTime(.0001,now+.04);ringAmp.gain.exponentialRampToValueAtTime(.06,now+.055);ringAmp.gain.exponentialRampToValueAtTime(.0001,now+.28);ring.connect(ringAmp);ringAmp.connect(audio.master);ring.start(now+.04);ring.stop(now+.3);}}
function moveSound(capture=false){ensureAudio();woodStrike(capture);}
function play(g,x,y){const r=Go.play(g.board,g.turn,x,y,g.keys);g.snapshots.push({board:g.board,turn:g.turn,captures:{...g.captures},last:g.last});g.board=r.board;g.captures[g.turn]+=r.captured;g.moves.push([g.turn,Go.toGtp(x,y,g.n)]);g.keys.push(Go.key(g.board));g.last=x===null?null:[x,y];moveSound(r.captured>0);g.turn=Go.other(g.turn);}
function undo(g){const s=g.snapshots.pop();if(!s)return;Object.assign(g,s);g.moves.pop();g.keys.pop();g.phase='play';g.dead.clear();g.recommendations=[];g.evalBlack=null;g.evalScore=null;g.aiPoorStreak=0;g.resignText='';}
function crop(g,full){if(full||!g.initial.length)return {x:0,y:0,count:g.n};const pts=[...g.initial.map(s=>s.slice(1)),...g.moves.filter(m=>m[1]!=='pass').map(m=>Go.fromGtp(m[1],g.n))];let x=Math.max(0,Math.min(...pts.map(p=>p[0]))-2),y=Math.max(0,Math.min(...pts.map(p=>p[1]))-2),maxx=Math.min(g.n-1,Math.max(...pts.map(p=>p[0]))+3),maxy=Math.min(g.n-1,Math.max(...pts.map(p=>p[1]))+3);const count=Math.min(g.n,Math.max(9,maxx-x+1,maxy-y+1));x=Math.min(x,g.n-count);y=Math.min(y,g.n-count);return {x,y,count};}
function draw(canvas,g,full=true,labels=[],hint=null){const c=canvas.getContext('2d'),w=canvas.width,v=crop(g,full),pad=58,step=(w-2*pad)/(v.count-1),wood=BOARD_THEMES[appearance.board]||BOARD_THEMES.bamboo,stones=STONE_THEMES[appearance.stones]||STONE_THEMES.classic;canvas.geom={...v,pad,step};c.clearRect(0,0,w,w);const surface=c.createLinearGradient(0,0,w,w);surface.addColorStop(0,wood.edge);surface.addColorStop(1,wood.base);c.fillStyle=surface;c.fillRect(0,0,w,w);c.strokeStyle=wood.line;c.lineWidth=1.3;
  if(wood.texture==='grain'){c.save();c.globalAlpha=.16;c.strokeStyle=wood.line;c.lineWidth=1;for(let y=-w;y<w*2;y+=34){c.beginPath();c.moveTo(0,y);c.bezierCurveTo(w*.25,y-14,w*.5,y+16,w,y-4);c.stroke();}c.restore();}else if(wood.texture==='slate'){c.save();c.globalAlpha=.1;c.strokeStyle=wood.edge;c.lineWidth=1;for(let i=-w;i<w*2;i+=54){c.beginPath();c.moveTo(i,0);c.lineTo(i+w*.4,w);c.stroke();c.beginPath();c.moveTo(0,i+w*.2);c.lineTo(w,i-w*.15);c.stroke();}c.restore();}
  for(let i=0;i<v.count;i++){let z=pad+i*step;c.beginPath();c.moveTo(pad,z);c.lineTo(w-pad,z);c.stroke();c.beginPath();c.moveTo(z,pad);c.lineTo(z,w-pad);c.stroke();}
  const stars=g.n===19?[3,9,15]:g.n===13?[3,6,9]:[2,4,6];for(const x of stars)for(const y of stars)if(x>=v.x&&y>=v.y&&x<v.x+v.count&&y<v.y+v.count){c.fillStyle=wood.star;c.beginPath();c.arc(pad+(x-v.x)*step,pad+(y-v.y)*step,3.2,0,Math.PI*2);c.fill();}
  c.font='16px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillStyle='#826b46';for(let i=0;i<v.count;i++){c.fillText('ABCDEFGHJKLMNOPQRST'[v.x+i],pad+i*step,w-23);c.fillText(String(g.n-v.y-i),24,pad+i*step);}
  for(let y=v.y;y<v.y+v.count;y++)for(let x=v.x;x<v.x+v.count;x++){const color=g.board[y][x];if(!color)continue;const px=pad+(x-v.x)*step,py=pad+(y-v.y)*step,r=step*.42;const grad=c.createRadialGradient(px-r*.3,py-r*.35,0,px,py,r);grad.addColorStop(0,color==='B'?stones.blackA:stones.whiteA);grad.addColorStop(1,color==='B'?stones.blackB:stones.whiteB);c.fillStyle=grad;c.shadowColor='#30251033';c.shadowBlur=3;c.shadowOffsetY=2;c.beginPath();c.arc(px,py,r,0,Math.PI*2);c.fill();c.shadowColor='transparent';c.strokeStyle=color==='B'?stones.blackLine:stones.whiteLine;c.lineWidth=1;c.stroke();if(g.dead.has(y*g.n+x)){c.strokeStyle='#a44434';c.lineWidth=3;c.beginPath();c.moveTo(px-r*.45,py-r*.45);c.lineTo(px+r*.45,py+r*.45);c.moveTo(px+r*.45,py-r*.45);c.lineTo(px-r*.45,py+r*.45);c.stroke();}}
  if(g.last){const [x,y]=g.last;c.strokeStyle=g.board[y][x]==='B'?'#d9ddcb':'#9b4837';c.lineWidth=2;c.beginPath();c.arc(pad+(x-v.x)*step,pad+(y-v.y)*step,step*.13,0,Math.PI*2);c.stroke();}
  for(const [x,y,t] of labels){if(x<v.x||y<v.y||x>=v.x+v.count||y>=v.y+v.count)continue;c.fillStyle=g.board[y][x]==='B'?'white':'#9b4837';c.font=`bold ${Math.max(13,step*.38)}px sans-serif`;c.fillText(t,pad+(x-v.x)*step,pad+(y-v.y)*step);}
  if(hint&&hint[0]!==null&&hint[0]>=v.x&&hint[1]>=v.y&&hint[0]<v.x+v.count&&hint[1]<v.y+v.count){c.strokeStyle='#984836';c.lineWidth=3;c.beginPath();c.arc(pad+(hint[0]-v.x)*step,pad+(hint[1]-v.y)*step,step*.3,0,Math.PI*2);c.stroke();}}
function point(canvas,e){const r=canvas.getBoundingClientRect(),g=canvas.geom,px=(e.clientX-r.left)*canvas.width/r.width,py=(e.clientY-r.top)*canvas.height/r.height,a=(px-g.pad)/g.step,b=(py-g.pad)/g.step;if(a<-.4||b<-.4||a>g.count-.6||b>g.count-.6)return null;return [Math.round(a)+g.x,Math.round(b)+g.y];}
function progress(){$('#progressCount').textContent=allPuzzles.filter(p=>studied.has(p.id)).length;if(current)$('#markStudied').textContent=studied.has(current.id)?'✓ 已研习 · 点击撤销':'标记已研习';}
function renderList(){const rows=filtered.slice(listPage*12,listPage*12+12),container=$('#puzzleList');container.replaceChildren();for(const p of rows){const b=document.createElement('button');b.className=current?.id===p.id?'selected':'';b.textContent=`第 ${p.number} 题 · ${p.category}`;const s=document.createElement('small');s.textContent=[p.difficulty,studied.has(p.id)?'✓':''].filter(Boolean).join(' · ');if(s.textContent)b.append(s);b.onclick=()=>loadPuzzle(p);container.append(b);}if(!rows.length)container.textContent='没有符合条件的题目';$('#listPage').textContent=`${filtered.length?listPage+1:0} / ${Math.ceil(filtered.length/12)} 页`;$('#prevList').disabled=listPage===0;$('#nextList').disabled=(listPage+1)*12>=filtered.length;}
function filter(){const difficulty=$('#difficultyFilter').value,search=$('#search').value.trim().toLowerCase();filtered=allPuzzles.filter(p=>p.mode==='solutions'&&(difficulty==='all'||p.difficulty===difficulty)&&(!search||`${p.number} ${p.sourceFile||''}`.toLowerCase().includes(search)));listPage=0;if(filtered.length)loadPuzzle(filtered[0]);else renderList();$('#puzzleNext').disabled=!filtered.length;}
function switchPage(p){clearTimeout(demoTimer);page=p==='battle'?'battle':p==='record'?'record':'solutions';$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#study').hidden=page!=='solutions';$('#battle').hidden=page!=='battle';$('#record').hidden=page!=='record';if(page==='battle'){renderBattle();if(!battle.started)openBattleSetup();return;}if(page==='record'){if(!record)newRecord();renderRecord();refreshRecords();return;}$('#progressLabel').textContent='已研习 / 420';$('#libraryTitle').textContent='标准答案题库 · 420';$('#search').value='';filter();}
function loadPuzzle(p){clearTimeout(demoTimer);puzzleEpoch++;current=p;puzzle=game(19,p.stones,p.player);$('#puzzleName').textContent=`第 ${p.number} 题`;$('#puzzleCategory').textContent=p.category;$('#puzzleGoal').textContent='按照标准变化推演';$('#bookName').textContent='Go Game Guru Weekly Problems · An Younggil 8段、David Ormerod';$('#sourceNumber').textContent=`第 ${p.number} 题 · 含 ${p.answerPaths.length} 条标注正确变化`;$('#sourceLink').href='https://github.com/gogameguru/go-problems';$('#sourceLink').textContent='查看 CC BY-NC-SA 4.0 来源 ↗';$('#answerScope').textContent='答案路径来自题库 SGF 中标注为 Correct 的变化；演示默认播放其中最短的一条正确变化。';$('#solutionDemo').disabled=false;$('#solutionDemo').textContent='演示标准答案';$('#puzzleAnalysis').textContent='AI 分析供参考，不等同于题库答案。';$('#puzzleAnalyze').disabled=false;$('#puzzleFeedback').textContent='自由推演：黑白交替落子。';
  if(sgfURL)URL.revokeObjectURL(sgfURL);const coords=c=>p.stones.filter(s=>s[0]===c).map(s=>'['+String.fromCharCode(97+s[1],97+s[2])+']').join('');const labels=p.labels?.length?'LB'+p.labels.map(s=>'['+String.fromCharCode(97+s[0],97+s[1])+':'+s[2]+']').join(''):'';const answer=p.answerPaths[0].map(m=>`;${m[0]}[${String.fromCharCode(97+m[1],97+m[2])}]`).join('');sgfURL=URL.createObjectURL(new Blob([`(;FF[4]GM[1]CA[UTF-8]SZ[19]PL[${p.player}]C[${p.book||'Go Game Guru'} ${p.chapter}-${p.number}]AB${coords('B')}AW${coords('W')}${labels}${answer})`],{type:'application/x-go-sgf'}));$('#downloadPuzzle').href=sgfURL;$('#downloadPuzzle').download=p.id+'.sgf';renderPuzzle();renderList();progress();}
function renderPuzzle(hint=null){draw($('#puzzleBoard'),puzzle,$('#fullBoard').checked,current.labels||[],hint);$('#puzzleTurn').textContent=`${current.player==='B'?'黑':'白'}先 · 当前${puzzle.turn==='B'?'黑':'白'}方落子 · 已推演 ${puzzle.moves.length} 手`;}
function puzzleMove(x,y){try{play(puzzle,x,y);puzzleEpoch++;$('#puzzleAnalyze').disabled=false;$('#puzzleAnalysis').textContent='局面已改变，可重新分析。';$('#puzzleFeedback').textContent=x===null?'已停一手':'已落子，可继续推演。';renderPuzzle();}catch(e){$('#puzzleFeedback').textContent=e.message;}}
function demoSolution(){if(!current?.answerPaths)return;clearTimeout(demoTimer);puzzleEpoch++;puzzle=game(19,current.stones,current.player);const steps=current.answerPaths[0],token=puzzleEpoch;let i=0;$('#solutionDemo').disabled=true;function next(){if(token!==puzzleEpoch)return;if(i>=steps.length){$('#puzzleFeedback').textContent=`标准答案演示完成，共 ${steps.length} 手。`;$('#solutionDemo').disabled=false;return;}const [color,x,y]=steps[i++];if(puzzle.turn!==color){$('#puzzleFeedback').textContent='答案棋谱的轮次异常，已停止。';$('#solutionDemo').disabled=false;return;}try{play(puzzle,x,y);$('#puzzleFeedback').textContent=`标准答案演示：第 ${i} / ${steps.length} 手`;renderPuzzle(x===null?null:[x,y]);demoTimer=setTimeout(next,600);}catch(e){$('#puzzleFeedback').textContent=e.message;$('#solutionDemo').disabled=false;}}next();}
async function analyze(g,limit,options={}){if(location.protocol==='file:')throw Error('请用“启动弈境.cmd”启动，或运行 node server.cjs');const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({size:g.n,initialStones:g.initial.map(([c,x,y])=>[c,Go.toGtp(x,y,g.n)]),initialPlayer:g.initialPlayer,moves:g.moves,visits:limit,...options}),signal:AbortSignal.timeout(125000)});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||'引擎不可用');return d;}
async function puzzleAnalyze(){const token=++puzzleEpoch;$('#puzzleAnalyze').disabled=true;$('#puzzleAnalysis').textContent=`KataGo 正在以 ${ANALYSIS_VISITS} 次深度分析…`;try{const d=await analyze(puzzle,ANALYSIS_VISITS);if(token!==puzzleEpoch)return;const m=d.moveInfos?.find(m=>m.order===0)||d.moveInfos?.[0];if(!m)throw Error('没有可用分析结果');$('#puzzleAnalysis').textContent=`AI 建议：${m.move}\n参考变化：${m.pv.join(' → ')}\n实际搜索 ${d.rootInfo.visits} 次。\n按全盘评估，可能选择脱先；不能据此判定局部死活。`;const pt=m.move==='pass'?null:Go.fromGtp(m.move,19);renderPuzzle(pt);}catch(e){if(token===puzzleEpoch)$('#puzzleAnalysis').textContent=e.message;}finally{if(token===puzzleEpoch)$('#puzzleAnalyze').disabled=false;}}
function normalizedWinrate(root){let n=Number(root?.winrate);if(!Number.isFinite(n))return null;if(n>1)n/=100;return Math.max(0,Math.min(1,n));}
function movePoint(move,n){return move&&move!=='pass'?Go.fromGtp(move,n):null;}
function updateBattleInsight(d,player){const root=d.rootInfo||{},raw=normalizedWinrate(root);if(raw!==null)battle.evalBlack=player==='B'?raw:1-raw;const score=Number(root.scoreLead);if(Number.isFinite(score))battle.evalScore=player==='B'?score:-score;battle.evalTurn=player;battle.recommendations=(d.moveInfos||[]).filter(m=>m.move&&m.move!=='pass').sort((a,b)=>(a.order??999)-(b.order??999)).slice(0,3).map(m=>({move:m.move,visits:m.visits||0,winrate:normalizedWinrate(m),scoreLead:Number.isFinite(Number(m.scoreLead))?(player==='B'?Number(m.scoreLead):-Number(m.scoreLead)):null}));}
function renderRecommendations(){const box=$('#battleRecommendations');box.replaceChildren();if(!battle.recommendations.length){box.textContent='点击按钮后显示当前局面的候选点。';return;}battle.recommendations.forEach((m,i)=>{const row=document.createElement('div');row.className='rec-row';const pt=movePoint(m.move,battle.n);row.innerHTML=`<b>${i+1}</b><span>${m.move}</span><small>${m.winrate===null?'—':(m.winrate*100).toFixed(1)+'%'}${m.visits?' · '+m.visits+'次':''}</small>`;row.title=pt?'棋盘上已标记候选点':'停一手';box.append(row);});}
function currentAiLevel(){const base=AI_LEVELS[battle?.config?.aiLevel]||AI_LEVELS.amateur;if(battle?.config?.aiLevel!=='ai')return base;return {...base,visits:battle.config.aiVisits||base.visits,temperature:Number(battle.config.aiTemperature||0),pvLen:battle.config.aiPVLen||12};}
function renderBattle(){const marks=battle.insightVisible?battle.recommendations.map((m,i)=>{const p=movePoint(m.move,battle.n);return p?[p[0],p[1],String(i+1)]:null;}).filter(Boolean):[];draw($('#battleBoard'),battle,true,marks);$('#moveCount').textContent=battle.moves.length;$('#blackCaptures').textContent=battle.captures.B;$('#whiteCaptures').textContent=battle.captures.W;const state=!battle.started?'等待开局设置':battle.resignText||(battle.busy?'KataGo 思考中':battle.phase==='scoring'?'请标记死子':battle.phase==='done'?'对局结束':battle.turn==='B'?'你的回合':'等待 AI 落子');$('#battleState').textContent=state;$('#battlePass').disabled=!battle.started||battle.busy||battle.turn!=='B'||battle.phase!=='play'||!engineReady||!!battle.resignText;$('#battleUndo').disabled=!battle.started||battle.busy||!battle.moves.length;$('#battleRetry').hidden=!battle.started||battle.busy||battle.turn!=='W'||battle.phase!=='play'||!!battle.resignText;$('#battleRecommend').disabled=!battle.started||battle.busy||battle.phase!=='play'||!engineReady||!!battle.resignText;$('#battleRecommend').textContent=battle.insightVisible?'隐藏形势与推荐':'显示形势与推荐';$('#battleInsight').hidden=!battle.insightVisible;$('#battleSettings').disabled=battle.busy;$('#scoreButton').hidden=battle.phase!=='scoring';const level=currentAiLevel();$('#boardSizeLabel').textContent=battle.started?`${battle.n} 路`:'等待设置';$('#aiLevelLabel').textContent=battle.started?level.name:'等待设置';$('#visitLabel').textContent=battle.started?`${level.visits} 次`:'等待设置';$('#analysisVisitLabel').textContent=`${ANALYSIS_VISITS} 次`;$('#resignLabel').textContent=battle.started?`第 ${battle.config.resignAfter} 手起`:'—';$('#resignRuleText').textContent=battle.started?`第 ${battle.config.resignAfter} 手起，白方自身胜率低于 ${battle.config.resignThreshold}% 连续 ${battle.config.resignStreak} 手时，AI 会投降。`:'请先开始一局以设置投降规则。';const pct=battle.evalBlack===null?50:battle.evalBlack*100;$('#battleEval').textContent=battle.evalBlack===null?'等待分析':`黑 ${pct.toFixed(1)}% · 白 ${(100-pct).toFixed(1)}%` ;$('#evalBlack').style.width=`${pct}%`;$('#evalText').textContent=battle.evalBlack===null?`点击按钮后由 KataGo 以 ${ANALYSIS_VISITS} 次深度评估；红色代表黑方胜率。`:`KataGo 评估${battle.evalScore===null?'':` · ${battle.evalScore>=0?'黑领先':'白领先'} ${Math.abs(battle.evalScore).toFixed(1)} 目`}${battle.aiPoorStreak?` · AI 劣势计数 ${battle.aiPoorStreak}/${battle.config.resignStreak}`:''}`;renderRecommendations();}
function setupValue(id,min,max,fallback){const n=Number($(id).value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function refreshAiLevelHint(){const level=AI_LEVELS[$('#aiLevel').value]||AI_LEVELS.amateur;$('#aiLevelHint').textContent=level.hint;$('#aiAdvanced').hidden=$('#aiLevel').value!=='ai';}
function populateBattleSetup(){const c=battle?.config||DEFAULT_BATTLE_CONFIG;$('#setupBoardSize').value=String(c.n||19);$('#aiLevel').value=c.aiLevel||'amateur';$('#aiVisits').value=String(c.aiVisits??256);$('#aiTemperature').value=String(c.aiTemperature??0);$('#aiPVLen').value=String(c.aiPVLen??12);refreshAiLevelHint();$('#resignAfter').value=c.resignAfter??150;$('#resignThreshold').value=c.resignThreshold??1;$('#resignStreak').value=c.resignStreak??12;}
function openBattleSetup(){populateBattleSetup();const dialog=$('#battleSetupDialog');if(!dialog.open)dialog.showModal();}
function startBattle(){const n=Number($('#setupBoardSize').value),aiLevel=AI_LEVELS[$('#aiLevel').value]?$('#aiLevel').value:'amateur',level=AI_LEVELS[aiLevel],c={n,aiLevel,aiVisits:Math.round(setupValue('#aiVisits',32,800,256)),aiTemperature:Number(setupValue('#aiTemperature',0,.3,0).toFixed(2)),aiPVLen:Math.round(setupValue('#aiPVLen',8,30,12)),resignAfter:Math.round(setupValue('#resignAfter',1,2000,150)),resignThreshold:Number(setupValue('#resignThreshold',.1,50,1).toFixed(1)),resignStreak:Math.round(setupValue('#resignStreak',1,100,12))};epoch++;battle=game(n);battle.config=c;battle.started=true;$('#battleSetupDialog').close();const effective=currentAiLevel();$('#battleFeedback').textContent=`黑先；本局 ${n} 路，对弈等级：${level.name}（${effective.visits} 次）；形势判断固定 ${ANALYSIS_VISITS} 次。`;$('#battleAnalysis').textContent='';renderBattle();}
function newBattle(){openBattleSetup();}
function weightedPick(items,weightOf){const weights=items.map(weightOf),total=weights.reduce((a,b)=>a+b,0);if(!(total>0))return items[0]||null;let r=Math.random()*total;for(let i=0;i<items.length;i++){r-=weights[i];if(r<=0)return items[i];}return items[items.length-1];}
function humanPolicyMove(policy,n,temperature=1){if(!Array.isArray(policy))return null;const moves=[];for(let i=0;i<n*n;i++){const p=Number(policy[i]);if(p>0)moves.push({move:Go.toGtp(i%n,Math.floor(i/n),n),human:true,prior:p});}return weightedPick(moves,m=>Math.pow(m.prior,1/temperature));}
function chooseAiMove(d,level){if(level.profile){const human=humanPolicyMove(d.humanPolicy,battle.n,level.temperature);if(human)return human;}const moves=(d.moveInfos||[]).filter(m=>m.move).sort((a,b)=>(a.order??999)-(b.order??999));if(!moves.length)return null;if(!(level.temperature>0))return moves[0];const pool=moves.slice(0,Math.min(5,moves.length));return weightedPick(pool,(m,i)=>Math.exp(-i/(level.temperature*2)));}
function checkPasses(){if(battle.moves.length>=2&&battle.moves.slice(-2).every(m=>m[1]==='pass')){battle.phase='scoring';$('#battleFeedback').textContent='连续停一手。点击棋块标记或取消死子，再确认结算。';return true;}return false;}
async function aiMove(){if(!battle.started||battle.busy||battle.turn!=='W'||battle.phase!=='play'||battle.resignText)return;const token=epoch,level=currentAiLevel();battle.busy=true;const start=performance.now();renderBattle();try{const options=level.profile?{humanProfile:level.profile}:{analysisPVLen:level.pvLen||12};const d=await analyze(battle,level.visits,options);if(token!==epoch)return;updateBattleInsight(d,'W');const raw=normalizedWinrate(d.rootInfo||{}),after=battle.moves.length>=battle.config.resignAfter,poor=after&&raw!==null&&raw<battle.config.resignThreshold/100;battle.aiPoorStreak=after?(poor?battle.aiPoorStreak+1:0):0;if(after&&poor&&battle.aiPoorStreak>=battle.config.resignStreak){battle.phase='done';battle.resignText='KataGo 判断白方投降';$('#battleFeedback').textContent=`白方自身胜率低于 ${battle.config.resignThreshold}% 已连续 ${battle.config.resignStreak} 手，AI 认输。`;return;}const m=chooseAiMove(d,level);if(!m)throw Error(level.profile?'Human SL 没有返回可用落点':'引擎没有返回落点');const pt=movePoint(m.move,battle.n);play(battle,pt?.[0]??null,pt?.[1]??null);battle.recommendations=[];battle.evalBlack=null;battle.evalScore=null;const moveInfo=m.human?`Human SL · ${level.name}人类棋谱概率落子`:level.temperature>0?`KataGo 候选随机 · ${level.temperature}`:'KataGo 一选';$('#battleAnalysis').textContent=`KataGo：${m.move}（${moveInfo}）\n${level.name} · 对弈搜索 ${d.rootInfo.visits} 次 · ${((performance.now()-start)/1000).toFixed(1)} 秒`;$('#battleFeedback').textContent=pt?'轮到你落子':'KataGo 停一手';checkPasses();}catch(e){if(token===epoch)$('#battleFeedback').textContent='AI 未落子：'+e.message+'。可重试或悔棋。';}finally{if(token===epoch){battle.busy=false;renderBattle();}}}
async function battleRecommend(){if(!battle.started||battle.busy||battle.phase!=='play'||!engineReady)return;if(battle.insightVisible){battle.insightVisible=false;renderBattle();return;}battle.insightVisible=true;if(battle.recommendations.length&&battle.evalBlack!==null){renderBattle();return;}const token=epoch,player=battle.turn;battle.busy=true;$('#battleFeedback').textContent=`KataGo 正在以 ${ANALYSIS_VISITS} 次深度计算形势与推荐…`;renderBattle();try{const d=await analyze(battle,ANALYSIS_VISITS);if(token!==epoch)return;updateBattleInsight(d,player);$('#battleFeedback').textContent=`已以 ${d.rootInfo.visits} 次深度显示当前局面的形势与前三推荐。`;}catch(e){if(token===epoch)$('#battleFeedback').textContent='分析失败：'+e.message;}finally{if(token===epoch){battle.busy=false;renderBattle();}}}
function battleMove(x,y){if(!battle.started||battle.busy||battle.turn!=='B'||battle.phase!=='play'||battle.resignText)return;if(!engineReady){$('#battleFeedback').textContent='KataGo 尚未就绪，请确认本地服务已启动。';return;}try{play(battle,x,y);battle.recommendations=[];battle.evalBlack=null;battle.evalScore=null;if(!checkPasses())aiMove();renderBattle();}catch(e){$('#battleFeedback').textContent=e.message;}}

function sgfPoint(value,n){const s=String(value??'').trim().toLowerCase();if(!s||s==='tt'||s==='pass')return null;if(!/^[a-s]{2}$/.test(s))return Go.fromGtp(String(value),n);const x=s.charCodeAt(0)-97,y=s.charCodeAt(1)-97;return x>=0&&y>=0&&x<n&&y<n?[x,y]:null;}
function importedPoint(value,n){if(Array.isArray(value)){if(value.length>=3)return [Number(value[1]),Number(value[2])];if(value.length===2&&Number.isFinite(Number(value[0]))&&Number.isFinite(Number(value[1])))return [Number(value[0]),Number(value[1])];}return sgfPoint(value,n);}
function normalizeImportedMove(item,n){const color=Array.isArray(item)?item[0]:item?.color||item?.player||item?.c;const value=Array.isArray(item)?item[1]:item?.move||item?.coord||item?.gtp;if(!['B','W'].includes(color))return null;const point=importedPoint(value,n);return [color,point?Go.toGtp(point[0],point[1],n):'pass'];}
function handicapPoints(n,h){const out=[];if(n<4)return out;const d=n<13?2:3,add=(x,y)=>out.push([x,y]);if(h>=2){add(n-d-1,d);add(d,n-d-1);}if(h>=3)add(n-d-1,n-d-1);if(h>=4)add(d,d);if(n%2&&h>=5)add((n-1)/2,(n-1)/2);if(n%2&&h>=6){add(d,(n-1)/2);add(n-d-1,(n-1)/2);}if(n%2&&h>=8){add((n-1)/2,d);add((n-1)/2,n-d-1);}return out.slice(0,Math.min(h,9));}
function parseGib(raw,filename=''){const lines=raw.split(/\r?\n/),initial=[],moves=[],meta={title:filename,black:'',white:'',result:'',date:''};let handicap=0;for(const source of lines){const line=source.trim(),upper=line.toUpperCase();if(upper.startsWith('\\[GAMEBLACKNAME='))meta.black=(line.match(/GAMEBLACKNAME=([^\\\]]+)/i)||[])[1]||'';if(upper.startsWith('\\[GAMEWHITENAME='))meta.white=(line.match(/GAMEWHITENAME=([^\\\]]+)/i)||[])[1]||'';if(upper.startsWith('INI')){const parts=line.split(/\s+/);handicap=Number(parts[3])||0;}if(upper.startsWith('STO')){const parts=line.split(/\s+/),color=parts[3]==='1'?'B':parts[3]==='2'?'W':null,x=Number(parts[4]),y=Number(parts[5]);if(color&&Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&y>=0&&x<19&&y<19)moves.push([color,Go.toGtp(x,y,19)]);}}for(const [x,y] of handicapPoints(19,handicap))initial.push(['B',x,y]);if(!moves.length)throw Error('GIB 中未找到有效落子');return {n:19,initialPlayer:'B',initial,moves,meta};}
function parseNgf(raw,filename=''){const lines=raw.split(/\r?\n/),n0=Number(lines[1]),n=[9,13,19].includes(n0)?n0:19,handicap=Number(lines[5])||0,meta={title:filename,black:(lines[3]||'').trim().split(/\s+/)[0]||'',white:(lines[2]||'').trim().split(/\s+/)[0]||'',result:'',date:(lines[8]||'').slice(0,8)},initial=handicapPoints(n,handicap).map(([x,y])=>['B',x,y]),moves=[];for(const source of lines){const line=source.trim().toUpperCase();if(line.slice(0,2)!=='PM'||line.length<7)continue;const color=line[4],x=line.charCodeAt(5)-65,y=line.charCodeAt(6)-65;if((color==='B'||color==='W')&&x>=1&&y>=1&&x<=n&&y<=n)moves.push([color,Go.toGtp(x-1,y-1,n)]);}if(!moves.length)throw Error('NGF 中未找到有效落子');return {n,initialPlayer:'B',initial,moves,meta};}
function parseSgf(text,filename=''){
  const raw=String(text||'').replace(/^\uFEFF/,'').trim();if(!raw)throw Error('棋谱内容为空');
  if(/\.gib$/i.test(filename)||/^\s*\\\[GAME/i.test(raw)||/\bSTO\s+\d+\s+\d+\s+\d+/i.test(raw))return parseGib(raw,filename);
  if(/\.ngf$/i.test(filename)||/^\s*NGF/i.test(raw))return parseNgf(raw,filename);
  if(raw[0]==='{'){try{const data=JSON.parse(raw),n=[9,13,19].includes(Number(data.size||data.n))?Number(data.size||data.n):19,initial=(data.initialStones||data.setup||[]).map(s=>{const c=Array.isArray(s)?s[0]:s.color;const p=importedPoint(Array.isArray(s)?s.slice(1):s.coord,n);return p&&['B','W'].includes(c)?[c,p[0],p[1]]:null;}).filter(Boolean),moves=(data.moves||[]).map(m=>normalizeImportedMove(m,n)).filter(Boolean);return {n,initialPlayer:data.initialPlayer==='W'?'W':'B',initial,moves,meta:{title:data.title||data.name||filename,black:data.black||data.PB||'',white:data.white||data.PW||''}};}catch(e){throw Error('JSON 棋谱无法解析：'+e.message);}}
  function readNode(i){const node={};i++;while(i<raw.length){while(/\s/.test(raw[i]||''))i++;if(!/[A-Za-z]/.test(raw[i]||''))break;let id='';while(/[A-Za-z]/.test(raw[i]||''))id+=raw[i++];while(/\s/.test(raw[i]||''))i++;if(raw[i]!=='[')break;const values=[];while(raw[i]==='['){i++;let value='';while(i<raw.length){if(raw[i]==='\\'&&i+1<raw.length){value+=raw[i+1];i+=2;continue;}if(raw[i]===']'){i++;break;}value+=raw[i++];}values.push(value);}node[id]=(node[id]||[]).concat(values);}return {node,next:i};}
  function readTree(i){while(i<raw.length&&raw[i]!=='(')i++;i++;const nodes=[];let branch=false;while(i<raw.length){if(raw[i]===';'){const r=readNode(i);nodes.push(r.node);i=r.next;continue;}if(raw[i]==='('){const r=readTree(i);if(!branch){nodes.push(...r.nodes);branch=true;}i=r.next;continue;}if(raw[i]===')')return {nodes,next:i+1};i++;}return {nodes,next:i};}
  let parsed;try{parsed=readTree(0).nodes;}catch{parsed=[];}if(!parsed.length)throw Error('未找到 SGF 棋谱节点');const root=parsed[0],sizeText=String(root.SZ?.[0]||'19').split(':')[0],n=[9,13,19].includes(Number(sizeText))?Number(sizeText):19,initial=[],occupied=new Set();let moveStarted=false;
  for(const node of parsed){for(const color of ['B','W'])for(const value of node[color]||[]){moveStarted=true;const p=sgfPoint(value,n);if(!p)continue;}}for(const node of parsed){if(moveStarted&&((node.B||[]).length||(node.W||[]).length))break;for(const color of ['AB','AW'])for(const value of node[color]||[]){const p=sgfPoint(value,n),c=color==='AB'?'B':'W';if(p&&!occupied.has(`${p[0]},${p[1]}`)){occupied.add(`${p[0]},${p[1]}`);initial.push([c,p[0],p[1]]);}}}
  const moves=[];for(const node of parsed)for(const color of ['B','W'])for(const value of node[color]||[]){const p=sgfPoint(value,n);moves.push([color,p?Go.toGtp(p[0],p[1],n):'pass']);}
  return {n,initialPlayer:root.PL?.[0]==='W'?'W':'B',initial,moves,meta:{title:root.GN?.[0]||filename,black:root.PB?.[0]||'',white:root.PW?.[0]||'',result:root.RE?.[0]||'',date:root.DT?.[0]||''}};
}
function collectInitial(g){const out=[];for(let y=0;y<g.n;y++)for(let x=0;x<g.n;x++)if(g.board[y][x])out.push([g.board[y][x],x,y]);return out;}
function applyRecordMove(g,color,move){if(g.turn!==color)g.turn=color;const p=movePoint(move,g.n),r=Go.play(g.board,color,p?.[0]??null,p?.[1]??null,g.keys);g.board=r.board;g.captures[color]+=r.captured;g.moves.push([color,move]);g.keys.push(Go.key(g.board));g.last=p;g.turn=Go.other(color);}
function rebuildRecord(){const old=record,g=game(old.n,old.initial||[],old.initialPlayer||'B');g.started=true;g.moveList=[...(old.moveList||[])];g.cursor=Math.max(0,Math.min(old.cursor??g.moveList.length,g.moveList.length));g.meta=old.meta||{};g.recordMode=old.recordMode||'play';for(const [color,move] of g.moveList.slice(0,g.cursor)){try{applyRecordMove(g,color,move);}catch{break;}}g.insightVisible=false;g.recommendations=[];g.evalBlack=null;record=g;}
function newRecord(n=19){record=game(n);record.started=true;record.moveList=[];record.cursor=0;record.meta={title:'',black:'',white:'',result:'',date:''};record.recordMode='play';if($('#recordMode'))$('#recordMode').value='play';renderRecord();}
function loadParsedRecord(parsed,filename=''){record=game(parsed.n,parsed.initial,parsed.initialPlayer);record.started=true;record.moveList=parsed.moves;record.cursor=parsed.moves.length;record.meta=parsed.meta||{title:filename};record.recordMode='play';if($('#recordSize'))$('#recordSize').value=String(parsed.n);if($('#recordMode'))$('#recordMode').value='play';rebuildRecord();$('#recordTitle').value=record.meta.title||filename.replace(/\.[^.]+$/,'');renderRecord();$('#recordFeedback').textContent=`已读取 ${filename||'棋谱'}，共 ${record.moveList.length} 手。`;
}
 function renderRecord(){if(!record)return;const marks=record.insightVisible?record.recommendations.map((m,i)=>{const p=movePoint(m.move,record.n);return p?[p[0],p[1],String(i+1)]:null;}).filter(Boolean):[];draw($('#recordBoard'),record,true,marks);$('#recordName').textContent=record.meta?.title||$('#recordTitle').value||'未命名棋谱';$('#recordTurn').textContent=record.recordMode==='setupB'?'摆黑子':record.recordMode==='setupW'?'摆白子':`${record.cursor} / ${record.moveList.length} 手 · ${record.turn==='B'?'黑方':'白方'}落子`;$('#recordState').textContent=record.moveList.length?`${record.cursor} / ${record.moveList.length} 手`:'新棋谱';$('#recordMeta').textContent=record.meta?.black||record.meta?.white?`黑：${record.meta.black||'未标注'}　白：${record.meta.white||'未标注'}${record.meta.result?'　结果：'+record.meta.result:''}`:'自行摆局或导入棋谱后，信息会显示在这里。';$('#recordAnalysis').textContent=record.evalBlack===null?'可以读取 SGF、GIB、NGF、JSON 或文本棋谱；腾讯围棋、野狐围棋导出的 SGF 可直接使用。':`当前局面黑方胜率约 ${(record.evalBlack*100).toFixed(1)}%${record.evalScore===null?'':`，形势 ${record.evalScore>=0?'黑领先':'白领先'} ${Math.abs(record.evalScore).toFixed(1)} 目。`}`;$('#recordAnalyze').textContent=record.insightVisible?'隐藏形势判断':`形势判断 · ${ANALYSIS_VISITS} 次`;$('#recordFirst').disabled=!record.cursor;$('#recordPrev').disabled=!record.cursor;$('#recordNext').disabled=record.cursor>=record.moveList.length;$('#recordLast').disabled=record.cursor>=record.moveList.length;}
function recordSetupClick(x,y){const color=record.recordMode==='setupW'?'W':'B';if(record.cursor||record.moveList.length){record.initial=[];record.moveList=[];record.cursor=0;rebuildRecord();}record.board[y][x]=record.board[y][x]===color?null:color;record.initial=collectInitial(record);record.keys=[Go.key(record.board)];record.turn='B';record.last=null;record.captures={B:0,W:0};renderRecord();}
function recordPlayClick(x,y){if(record.cursor<record.moveList.length)record.moveList.splice(record.cursor);try{play(record,x,y);record.moveList.push(record.moves[record.moves.length-1]);record.cursor++;record.insightVisible=false;record.recommendations=[];record.evalBlack=null;record.evalScore=null;renderRecord();}catch(e){$('#recordFeedback').textContent=e.message;}}
function recordBoardClick(x,y){if(record.recordMode==='setupB'||record.recordMode==='setupW')recordSetupClick(x,y);else recordPlayClick(x,y);}
function navigateRecord(cursor){record.cursor=Math.max(0,Math.min(cursor,record.moveList.length));rebuildRecord();renderRecord();}
function escapeSgf(value){return String(value??'').replace(/\\/g,'\\\\').replace(/\]/g,'\\]');}
function gtpToSgf(move,n){const p=movePoint(move,n);return p?String.fromCharCode(97+p[0],97+p[1]):'';}
function serializeSgf(g,title='弈境棋谱'){const setup=collectInitial({n:g.n,board:(g.initial||[]).reduce((b,[c,x,y])=>(b[y][x]=c,b),Go.empty(g.n))}),moves=g.moveList||g.moves||[],meta=g.meta||{};const ab=setup.filter(s=>s[0]==='B').map(s=>`[${String.fromCharCode(97+s[1],97+s[2])}]`).join(''),aw=setup.filter(s=>s[0]==='W').map(s=>`[${String.fromCharCode(97+s[1],97+s[2])}]`).join('');const root=`(;FF[4]GM[1]CA[UTF-8]SZ[${g.n}]KM[7.5]GN[${escapeSgf(title)}]PB[${escapeSgf(meta.black||'玩家')}]PW[${escapeSgf(meta.white||'KataGo')}]${g.initialPlayer==='W'?'PL[W]':''}${ab?`AB${ab}`:''}${aw?`AW${aw}`:''}`;return root+moves.map(m=>`;${m[0]}[${m[1]==='pass'?'':gtpToSgf(m[1],g.n)}]`).join('')+')';}
async function saveRecordToFolder(g,defaultName='棋谱'){if(!g?.started){$('#battleFeedback').textContent='请先开始一局。';return;}const title=prompt('请输入保存的棋谱名称',g.meta?.title||defaultName);if(title===null)return;const name=title.trim()||defaultName,fileName=/\.[a-z0-9]{2,5}$/i.test(name)?name:`${name}.sgf`;try{const content=serializeSgf(g,name),r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:fileName,content})}),d=await r.json();if(!r.ok)throw Error(d.error||'保存失败');if(g===battle)$('#battleFeedback').textContent=`棋谱已保存：${d.name}`;else $('#recordFeedback').textContent=`棋谱已保存：${d.name}`;refreshRecords();}catch(e){const target=g===battle?$('#battleFeedback'):$('#recordFeedback');target.textContent='棋谱保存失败：'+e.message;}}
function downloadRecord(){if(!record)return;const a=document.createElement('a'),title=$('#recordTitle').value.trim()||'弈境棋谱';a.href=URL.createObjectURL(new Blob([serializeSgf(record,title)],{type:'application/x-go-sgf'}));a.download=title.replace(/[\\/:*?"<>|]/g,'_')+'.sgf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function refreshRecords(){const select=$('#savedRecordList');if(!select)return;try{const r=await fetch('/api/records');const d=await r.json();select.replaceChildren(new Option('选择 Go/records 中的棋谱',''));for(const item of d.records||[])select.add(new Option(`${item.name} · ${(item.size/1024).toFixed(1)} KB`,item.name));}catch{select.replaceChildren(new Option('本地服务未连接',''));}}
 async function analyzeRecord(){if(!record||record.busy)return;if(record.insightVisible){record.insightVisible=false;renderRecord();return;}record.busy=true;$('#recordFeedback').textContent=`KataGo 正在以 ${ANALYSIS_VISITS} 次深度分析当前局面…`;renderRecord();try{const d=await analyze(record,ANALYSIS_VISITS);const root=d.rootInfo||{},raw=normalizedWinrate(root);record.evalBlack=raw===null?null:record.turn==='B'?raw:1-raw;const score=Number(root.scoreLead);record.evalScore=Number.isFinite(score)?record.turn==='B'?score:-score:null;record.recommendations=(d.moveInfos||[]).filter(m=>m.move&&m.move!=='pass').sort((a,b)=>(a.order??999)-(b.order??999)).slice(0,3);record.insightVisible=true;$('#recordFeedback').textContent=`已完成形势判断，实际搜索 ${d.rootInfo?.visits||ANALYSIS_VISITS} 次。`;}catch(e){$('#recordFeedback').textContent='分析失败：'+e.message;}finally{record.busy=false;renderRecord();}}
async function readRecordFile(file){try{loadParsedRecord(parseSgf(await file.text(),file.name),file.name);}catch(e){$('#recordFeedback').textContent='读取失败：'+e.message;}}
async function loadSavedRecord(){const name=$('#savedRecordList').value;if(!name)return;try{const r=await fetch('/api/records/file?name='+encodeURIComponent(name)),text=await r.text();if(!r.ok)throw Error(JSON.parse(text).error||'读取失败');loadParsedRecord(parseSgf(text,name),name);}catch(e){$('#recordFeedback').textContent='读取失败：'+e.message;}}

$$('[data-page]').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));$('#difficultyFilter').onchange=filter;$('#search').oninput=filter;$('#prevList').onclick=()=>{listPage--;renderList();};$('#nextList').onclick=()=>{listPage++;renderList();};$('#puzzleNext').onclick=()=>{const p=filtered[(filtered.findIndex(p=>p.id===current.id)+1)%filtered.length];if(p){listPage=Math.floor(filtered.indexOf(p)/12);loadPuzzle(p);}};$('#fullBoard').onchange=()=>renderPuzzle();$('#puzzleBoard').onclick=e=>{const p=point(e.currentTarget,e);if(p)puzzleMove(...p);};$('#puzzlePass').onclick=()=>puzzleMove(null,null);$('#puzzleReset').onclick=()=>loadPuzzle(current);$('#puzzleUndo').onclick=()=>{puzzleEpoch++;undo(puzzle);$('#puzzleAnalyze').disabled=false;$('#puzzleAnalysis').textContent='已退一步，可重新分析。';renderPuzzle();};$('#solutionDemo').onclick=demoSolution;$('#puzzleAnalyze').onclick=puzzleAnalyze;
$('#markStudied').onclick=()=>{studied.has(current.id)?studied.delete(current.id):studied.add(current.id);try{localStorage.setItem('yijing.studied.v2',JSON.stringify([...studied]));}catch{$('#puzzleFeedback').textContent='浏览器不允许保存进度，本次进度仅保留到关闭页面。';}progress();renderList();};
$('#battleBoard').onclick=e=>{const p=point(e.currentTarget,e);if(!p)return;if(battle.phase==='scoring'){const [x,y]=p;if(battle.board[y][x]){const g=Go.group(battle.board,x,y),remove=battle.dead.has(y*battle.n+x);for(const [a,b] of g.stones)remove?battle.dead.delete(b*battle.n+a):battle.dead.add(b*battle.n+a);renderBattle();}return;}battleMove(...p);};$('#battlePass').onclick=()=>battleMove(null,null);$('#battleRetry').onclick=aiMove;$('#battleRecommend').onclick=battleRecommend;$('#battleSave').onclick=()=>saveRecordToFolder(battle,'人机对弈');$('#battleRestart').onclick=openBattleSetup;$('#battleSettings').onclick=openBattleSetup;$('#battleUndo').onclick=()=>{if(battle.busy)return;epoch++;do{undo(battle);}while(battle.moves.length&&battle.turn!=='B');$('#battleFeedback').textContent='已回退到你的上一手';$('#battleAnalysis').textContent='';renderBattle();};
$('#scoreButton').onclick=()=>{const b=battle.board.map(r=>r.slice());for(const k of battle.dead)b[Math.floor(k/battle.n)][k%battle.n]=null;const score=Go.area(b);battle.phase='done';$('#battleFeedback').textContent=`数子结果：黑 ${score.B}，白 ${score.W}（含贴目）。${score.B>score.W?'黑':'白'}胜 ${Math.abs(score.B-score.W)} 目。`;renderBattle();};
$('#recordNew').onclick=()=>newRecord(Number($('#recordSize').value));$('#recordSize').onchange=()=>newRecord(Number($('#recordSize').value));$('#recordMode').onchange=e=>{if(record){record.recordMode=e.target.value;renderRecord();}};$('#recordBoard').onclick=e=>{const p=point(e.currentTarget,e);if(p)recordBoardClick(...p);};$('#recordFirst').onclick=()=>navigateRecord(0);$('#recordPrev').onclick=()=>navigateRecord(record.cursor-1);$('#recordNext').onclick=()=>navigateRecord(record.cursor+1);$('#recordLast').onclick=()=>navigateRecord(record.moveList.length);$('#recordAnalyze').onclick=analyzeRecord;$('#recordSave').onclick=()=>saveRecordToFolder(record,'打谱棋谱');$('#recordDownload').onclick=downloadRecord;$('#recordFile').onchange=e=>{const file=e.target.files?.[0];if(file)readRecordFile(file);e.target.value='';};$('#recordRefresh').onclick=refreshRecords;$('#recordLoadSaved').onclick=loadSavedRecord;
function redrawForAppearance(){if(puzzle)renderPuzzle();if(battle)renderBattle();}
function saveAppearance(){try{localStorage.setItem('yijing.appearance.v1',JSON.stringify(appearance));}catch{}}
$('#boardTheme').value=appearance.board;$('#stoneTheme').value=appearance.stones;$('#boardTheme').onchange=e=>{appearance.board=e.target.value;saveAppearance();redrawForAppearance();};$('#stoneTheme').onchange=e=>{appearance.stones=e.target.value;saveAppearance();redrawForAppearance();};
function refreshAnalysisDepth(){const value=String(ANALYSIS_VISITS);if($('#analysisVisits'))$('#analysisVisits').value=value;if($('#analysisDepthValue'))$('#analysisDepthValue').textContent=`${ANALYSIS_VISITS} 次`;if($('#analysisDepthNote'))$('#analysisDepthNote').textContent=`题库、打谱和对局形势判断均使用 ${ANALYSIS_VISITS} 次搜索；不改变人机对弈难度。`;if(record)renderRecord();if(battle)renderBattle();}
$('#analysisVisits').value=String(ANALYSIS_VISITS);$('#analysisVisits').onchange=e=>{const next=Number(e.target.value);if(!ANALYSIS_VISIT_OPTIONS.includes(next))return;ANALYSIS_VISITS=next;try{localStorage.setItem('yijing.analysisVisits.v1',String(next));}catch{}refreshAnalysisDepth();};
$('#bgmMode').onchange=e=>{audio.mode=e.target.value;audio.bgmEnabled=audio.mode!=='none';stopBgm();if(audio.bgmEnabled)ensureAudio();};$('#volumeRange').oninput=e=>{audio.volume=Number(e.target.value);if(audio.master)audio.master.gain.value=audio.volume;};document.addEventListener('pointerdown',()=>ensureAudio(),{passive:true});
$('#aiLevel').onchange=refreshAiLevelHint;$('#battleSetupForm').onsubmit=e=>{e.preventDefault();startBattle();};$('#setupCancel').onclick=()=>{if($('#battleSetupDialog').open)$('#battleSetupDialog').close();if(!battle.started)switchPage('solutions');};
$('#appExit').onclick=async()=>{if(!confirm('结束弈境并关闭后台 KataGo？'))return;$('#appExit').disabled=true;$('#appExit').textContent='正在结束…';try{await fetch('/api/shutdown',{method:'POST'});$('#engineStatus').textContent='弈境已结束';setTimeout(()=>location.replace('about:blank'),250);}catch{$('#appExit').disabled=false;$('#appExit').textContent='结束程序';}};
const splashStarted=performance.now();let splashDismissed=false,splashTimer=null;
function dismissSplash(){if(splashDismissed)return;splashDismissed=true;const splash=$('#loadingScreen');if(!splash)return;splash.classList.add('leaving');setTimeout(()=>splash.remove(),760);}
function releaseSplashWhenReady(){if(splashDismissed||!engineReady)return;clearTimeout(splashTimer);splashTimer=setTimeout(dismissSplash,Math.max(0,3400-(performance.now()-splashStarted)));}
setTimeout(()=>{if(!splashDismissed&&!engineReady)setTimeout(dismissSplash,800);},3400);
async function status(){try{if(location.protocol==='file:')throw Error('请通过启动脚本连接 KataGo');const r=await fetch('/api/status');const s=await r.json();engineReady=s.ready;$('#engineStatus').textContent=s.ready?'KataGo · CPU 已就绪':s.running?'KataGo 模型加载中':s.error||'引擎未启动';$('#engineStatus').classList.toggle('ready',s.ready);releaseSplashWhenReady();}catch{engineReady=false;$('#engineStatus').textContent='离线研习 · 对弈请启动本地服务';}if(battle)renderBattle();}
battle=game(DEFAULT_BATTLE_CONFIG.n);battle.config={...DEFAULT_BATTLE_CONFIG};refreshAnalysisDepth();renderBattle();switchPage('solutions');status();setInterval(status,10000);
