'use strict';
(function(){
  const KEY='yijing.language.v1';
  let lang='zh';try{lang=localStorage.getItem(KEY)==='en'?'en':'zh';}catch{}
  const pick=(zh,en)=>lang==='en'?en:zh;
  const text=(selector,zh,en)=>{const el=document.querySelector(selector);if(el)el.textContent=pick(zh,en);};
  const texts=(selector,values)=>{document.querySelectorAll(selector).forEach((el,i)=>{if(values[i])el.textContent=pick(values[i][0],values[i][1]);});};
  const attr=(selector,name,zh,en)=>{const el=document.querySelector(selector);if(el)el.setAttribute(name,pick(zh,en));};
  const label=(id,zh,en)=>{const el=document.getElementById(id),node=el?.closest('label');if(!node)return;for(const child of node.childNodes)if(child.nodeType===3&&child.textContent.trim()){child.textContent=pick(zh,en)+' ';break;}};
  const options=(id,values)=>{const el=document.getElementById(id);if(!el)return;[...el.options].forEach((option,i)=>{if(values[i])option.textContent=pick(values[i][0],values[i][1]);});};
  const difficulty={all:['全部难度','All difficulties'],入门:['入门','Beginner'],进阶:['进阶','Intermediate'],挑战:['挑战','Challenge']};
  const category={标准解答:['标准解答','Standard solution'],入门:['入门','Beginner'],进阶:['进阶','Intermediate'],挑战:['挑战','Challenge']};
  const levelNames={beginner:['新手 · 人类20级','Beginner · Human 20k'],human10k:['入门 · 人类10级','Starter · Human 10k'],veteran:['老手 · 人类5级','Experienced · Human 5k'],amateur:['业余高手 · 人类1段','Strong amateur · Human 1d'],amateur5d:['业余顶尖 · 人类5段','Top amateur · Human 5d'],pro:['职业棋手 · 职业九段','Professional · Pro 9d'],ai:['AI · KataGo 一选','AI · KataGo top choice']};
  function applyStatic(){
    document.documentElement.lang=lang==='en'?'en':'zh-CN';document.title=pick('弈境 · 围棋研习','Yijing · Go Studio');
    text('.brand span','围棋研习','Go Studio');texts('nav button',[['标准题库','Problems'],['打谱','Game Review'],['人机对弈','AI Match']]);attr('nav','aria-label','主导航','Main navigation');
    text('.scene-menu:not(.analysis-menu) summary','棋具 · 声音','Board · Sound');text('.analysis-menu summary','形势深度','Analysis depth');text('#appExit','结束程序','Exit');attr('#appExit','title','关闭网页服务及 KataGo','Stop the local service and KataGo');
    label('boardTheme','棋盘','Board');options('boardTheme',[['暖竹棋盘','Bamboo'],['深木棋盘','Walnut'],['宣纸棋盘','Rice paper'],['朱漆木纹棋盘','Red lacquer wood'],['青石棋盘','Bluestone']]);label('stoneTheme','棋子','Stones');options('stoneTheme',[['云子','Yunzi'],['青玉','Jade'],['墨白','Ink & ivory'],['琥珀云子','Amber Yunzi'],['青花瓷子','Blue-and-white porcelain']]);label('bgmMode','音景','Soundscape');options('bgmMode',[['风雨声','Rain and wind'],['松风','Pine wind'],['山涧流水','Mountain stream'],['古琴','Guqin'],['竹林夜雨','Bamboo night rain'],['静默','Silent']]);label('volumeRange','音量','Volume');label('analysisVisits','分析搜索量','Analysis visits');options('analysisVisits',[['64 次','64 visits'],['96 次','96 visits'],['256 次','256 visits'],['512 次','512 visits'],['800 次','800 visits'],['1200 次','1200 visits']]);
    texts('#study .heading .eyebrow',[['标准题库 / 含答案演示','PROBLEMS / ANSWER DEMOS']]);text('#study h1','静心，解一题。','Pause. Solve one.');text('#study .heading .muted','420 道带解答树的练习，随时查看正确变化与演示。','420 problems with answer trees and step-by-step demonstrations.');text('#progressLabel','已研习 / 420','Studied / 420');
    text('#libraryTitle','标准答案题库 · 420','Solved problems · 420');label('difficultyFilter','练习难度','Difficulty');options('difficultyFilter',[difficulty.all,difficulty.入门,difficulty.进阶,difficulty.挑战]);text('#study .library .tiny','题目来自公开 SGF 题库，答案以原文件标注的 Correct 变化为准。','Problems come from public SGF records; answers follow variations marked “Correct” in the source files.');label('search','查找题号','Find problem');attr('#search','placeholder','例如 12','e.g. 12');attr('#prevList','aria-label','上一页题目','Previous problems');attr('#nextList','aria-label','下一页题目','Next problems');
    label('fullBoard','完整棋盘','Full board');attr('#puzzleBoard','aria-label','题目棋盘，点击交叉点落子','Problem board; click an intersection to play');texts('#study .controls button',[['退一步','Undo'],['重置','Reset'],['停一手','Pass'],['下一题 →','Next →']]);text('#sourceLink','查看整理来源 ↗','View source ↗');text('#downloadPuzzle','下载本题 SGF ↓','Download SGF ↓');texts('#study .details h3',[['题目出处','Source'],['答案与推演','Answer & review']]);text('#answerScope','答案路径来自题库 SGF 中标注为 Correct 的变化，可播放演示，也可以自行推演。','Answer paths come from variations marked “Correct” in the source SGF. Play the demonstration or review freely.');text('#solutionDemo','演示标准答案','Show standard answer');text('#puzzleAnalyze','KataGo 分析当前局面','Analyze with KataGo');text('#puzzleAnalysis','AI 分析供参考，不等同于题库答案。','AI analysis is for reference and is not the source answer.');text('#markStudied','标记已研习','Mark as studied');
    texts('#battle .heading .eyebrow',[['黑白之间 / KATAGO','BETWEEN BLACK AND WHITE / KATAGO']]);text('#battle h1','手谈一局。','Play a game.');text('#battle .heading .muted','执黑先行，白贴 7.5 目。','You play Black; White receives 7.5 komi.');texts('#battle .board-heading span',[['● 你 · 黑方','● You · Black'],['○ KataGo · 白方','○ KataGo · White']]);attr('#battleBoard','aria-label','对战棋盘','Game board');texts('#battle .controls button',[['悔棋','Undo'],['停一手','Pass'],['重试 AI 落子','Retry AI move'],['新的一局','New game']]);text('#battle .details h2','本局设置','Game settings');label('setupBoardSize','棋盘大小','Board size');options('setupBoardSize',[['9 路 · 快速练习','9×9 · Quick game'],['13 路','13×13'],['19 路 · 标准棋盘','19×19 · Standard board']]);label('resignAfter','投降检测起始手数','Start resignation check at move');label('resignThreshold','自身胜率低于','Own win rate below');label('resignStreak','连续低胜率手数','Consecutive low-rate moves');text('#battleSettings','新局设置','New game settings');text('#battleRecommend','显示形势与推荐','Show evaluation & recommendations');text('#battleSave','保存本局棋谱','Save game record');text('#battle .details .tiny','本局参数在开局后锁定；如需修改，请重新开始一局。','Game settings are locked after the first move; start a new game to change them.');text('#battle .details .tiny:nth-of-type(2)','形势判断和前三推荐使用顶部菜单设置的搜索深度，独立于对弈难度。','Evaluation and top-three recommendations use the depth set in the top menu, independently of match strength.');texts('#battle dl dt',[['当前手数','Moves'],['黑方提子','Black captures'],['白方提子','White captures']]);text('#scoreButton','确认死子并结算','Confirm dead stones & score');
    texts('#record .heading .eyebrow',[['自由摆局 / 棋谱研习','FREE PLAY / GAME REVIEW']]);text('#record h1','落子成谱。','Build a record.');text('#record .heading .muted','自行摆放初始棋子、逐手打谱，并用 KataGo 检查当前局面的形势。','Set up stones, review moves, and check the position with KataGo.');label('recordSize','棋盘','Board');options('recordSize',[['9 路','9×9'],['13 路','13×13'],['19 路','19×19']]);label('recordMode','编辑方式','Edit mode');options('recordMode',[['摆黑子','Place black stones'],['摆白子','Place white stones'],['按次序落子','Play moves']]);text('#recordNew','新建棋谱','New record');label('recordFile','读取文件','Open file');options('savedRecordList',[['选择 Go/records 中的棋谱','Select a record from Go/records']]);text('#recordRefresh','刷新','Refresh');text('#recordLoadSaved','读取','Open');attr('#recordBoard','aria-label','打谱棋盘，点击交叉点编辑','Review board; click an intersection to edit');texts('#record .controls button',[['第一手','First'],['上一手','Previous'],['下一手','Next'],['最后一手','Last']]);text('#recordFeedback','摆子模式下点击空点落子，再次点击可清除。','In setup mode, click an empty point to place a stone; click again to remove it.');text('#record .details h2','棋谱工具','Record tools');label('recordTitle','棋谱名称','Record name');attr('#recordTitle','placeholder','例如 2026-09-06 人机对局','e.g. 2026-09-06 AI game');text('#recordAnalyze','形势判断','Evaluate position');text('#recordSave','保存到 Go/records','Save to Go/records');text('#recordDownload','下载 SGF','Download SGF');text('#record .details h3:nth-of-type(1)','当前局面','Current position');text('#recordAnalysis','可以读取 SGF、GIB、NGF、JSON 或文本棋谱；腾讯围棋、野狐围棋导出的 SGF 可直接使用。','SGF, GIB, NGF, JSON, and text records are supported, including exports from Tencent Go and Fox Go.');text('#record .details h3:nth-of-type(2)','棋谱信息','Record information');text('#recordMeta','尚未读取棋谱。','No record loaded.');text('#record .details h3:nth-of-type(3)','使用提示','Tips');text('#record .details .tiny','“摆黑子 / 摆白子”用于设置让子或局面；切换到“按次序落子”后可继续打谱。读取棋谱时默认显示最后一手，可用上方按钮浏览。','Use “Place black/white stones” for handicap or setup positions. Switch to “Play moves” to continue reviewing. Imported records open at the last move; use the controls to browse.');
    text('footer span','弈境 · 留白，落子。','Yijing · Leave space, then play.');text('footer a','题库与引擎来源','Sources & licenses');
    text('#battleSetupDialog h2','新局设置','New game settings');text('#battleSetupDialog .muted','这些参数只在开局前设置，对局中保持不变。','These settings apply before the game and remain fixed during play.');label('aiLevel','对弈等级','Match strength');options('aiLevel',[['新手 · 人类 20 级','Beginner · Human 20k'],['入门 · 人类10级','Starter · Human 10k'],['老手 · 人类 5 级','Experienced · Human 5k'],['业余高手 · 人类 1 段','Strong amateur · Human 1d'],['业余顶尖 · 人类5段','Top amateur · Human 5d'],['职业棋手 · 职业九段','Professional · Pro 9d'],['AI · KataGo 一选','AI · KataGo top choice']]);label('aiVisits','计算深度','Search depth');options('aiVisits',[['32 次','32 visits'],['64 次','64 visits'],['96 次','96 visits'],['256 次','256 visits'],['800 次','800 visits']]);label('aiTemperature','落子随机性','Move randomness');options('aiTemperature',[['关闭 · 一选','Off · top choice'],['轻微','Light'],['适度','Moderate']]);label('aiPVLen','变化长度','Variation length');options('aiPVLen',[['8 手','8 moves'],['12 手','12 moves'],['20 手','20 moves'],['30 手','30 moves']]);text('#aiAdvanced legend','AI 档自定义参数','AI custom parameters');text('#battleSetupDialog .tiny','入门、人类10级、业余顶尖、人类5段、职业棋手、职业九段均使用 Human SL 人类棋谱模型，按不同等级的落子分布与计算量逐级增强；AI 档可在这里自行调整 KataGo 搜索深度、随机性和变化长度。形势判断搜索量可在顶部菜单独立调整。','Starter, Human 10k, Top amateur, Human 5d, Professional, and Pro 9d use the Human SL model with progressively stronger move distributions and search. The AI level lets you adjust KataGo depth, randomness, and variation length. Evaluation depth is set in the top menu.');text('#setupCancel','取消','Cancel');text('#battleSetupForm button[type="submit"]','开始对局','Start game');
    text('#analysisDepthNote','题库、打谱和对局形势判断均使用 800 次搜索；不改变人机对弈难度。','Problems, game review, and match evaluation use 800 visits; this does not change match strength.');
    const dialogNote=document.querySelector('#battleSetupDialog form > p.tiny');if(dialogNote)dialogNote.textContent=pick('入门、人类10级、业余顶尖、人类5段、职业棋手、职业九段均使用 Human SL 人类棋谱模型，按不同等级的落子分布与计算量逐级增强；AI 档可在这里自行调整 KataGo 搜索深度、随机性和变化长度。形势判断搜索量可在顶部菜单独立调整。','Starter, Human 10k, Top amateur, Human 5d, Professional, and Pro 9d use the Human SL model with progressively stronger move distributions and search. The AI level lets you adjust KataGo depth, randomness, and variation length. Evaluation depth is set in the top menu.');const toggle=document.getElementById('languageToggle');if(toggle){toggle.textContent=lang==='en'?'中':'EN';toggle.title=pick('切换到英文界面','Switch to Chinese');}
  }
  function translateCategory(value){return category[value]?pick(...category[value]):value;}
  function translateLevel(id){return levelNames[id]?pick(...levelNames[id]):id;}
  function applyDynamic(){
    const en=lang==='en';
    try{
      if(typeof allPuzzles!=='undefined'){
        document.querySelectorAll('#puzzleList button').forEach((button,i)=>{const p=filtered[listPage*12+i];if(!p)return;button.firstChild.textContent=pick(`第 ${p.number} 题 · ${p.category}`,`Problem ${p.number} · ${translateCategory(p.category)}`);const small=button.querySelector('small');if(small)small.textContent=[translateCategory(p.difficulty),studied.has(p.id)?'✓':''].filter(Boolean).join(' · ');});
        document.getElementById('listPage').textContent=`${filtered.length?listPage+1:0} / ${Math.ceil(filtered.length/12)} ${en?'pages':'页'}`;
        document.getElementById('progressLabel').textContent=pick('已研习 / 420','Studied / 420');document.getElementById('libraryTitle').textContent=pick('标准答案题库 · 420','Solved problems · 420');
      }
      if(typeof current!=='undefined'&&current){const p=current;document.getElementById('puzzleName').textContent=pick(`第 ${p.number} 题`,`Problem ${p.number}`);document.getElementById('puzzleCategory').textContent=translateCategory(p.category);document.getElementById('puzzleGoal').textContent=pick('按照标准变化推演','Follow the standard variation');document.getElementById('puzzleTurn').textContent=en?`${p.player==='B'?'Black':'White'} first · ${puzzle.turn==='B'?'Black':'White'} to play · ${puzzle.moves.length} moves played`:`${p.player==='B'?'黑':'白'}先 · 当前${puzzle.turn==='B'?'黑':'白'}方落子 · 已推演 ${puzzle.moves.length} 手`;document.getElementById('sourceNumber').textContent=en?`Problem ${p.number} · ${p.answerPaths.length} Correct variations`:`第 ${p.number} 题 · 含 ${p.answerPaths.length} 条标注正确变化`;document.getElementById('markStudied').textContent=studied.has(p.id)?pick('✓ 已研习 · 点击撤销','✓ Studied · click to undo'):pick('标记已研习','Mark as studied');
      }
      if(typeof battle!=='undefined'&&battle){const level=typeof currentAiLevel==='function'?currentAiLevel():null;const state=!battle.started?pick('等待开局设置','Waiting for game settings'):battle.resignText||(battle.busy?pick('KataGo 思考中','KataGo is thinking'):battle.phase==='scoring'?pick('请标记死子','Mark dead stones'):battle.phase==='done'?pick('对局结束','Game over'):battle.turn==='B'?pick('你的回合','Your turn'):pick('等待 AI 落子','Waiting for AI'));document.getElementById('battleState').textContent=state;document.getElementById('analysisVisitLabel').textContent=`${ANALYSIS_VISITS} ${en?'visits':'次'}`;document.getElementById('resignLabel').textContent=battle.started?pick(`第 ${battle.config.resignAfter} 手起`,`From move ${battle.config.resignAfter}`):'—';document.getElementById('resignRuleText').textContent=battle.started?(en?`From move ${battle.config.resignAfter}, KataGo resigns when White's own win rate stays below ${battle.config.resignThreshold}% for ${battle.config.resignStreak} moves.`:`第 ${battle.config.resignAfter} 手起，白方自身胜率低于 ${battle.config.resignThreshold}% 连续 ${battle.config.resignStreak} 手时，AI 会投降。`):pick('请先开始一局以设置投降规则。','Start a game to set the resignation rule.');document.getElementById('battleRecommend').textContent=battle.insightVisible?pick('隐藏形势与推荐','Hide evaluation & recommendations'):pick('显示形势与推荐','Show evaluation & recommendations');document.getElementById('battleSave').textContent=pick('保存本局棋谱','Save game record');document.getElementById('battleAnalysis').textContent=translateMessage(document.getElementById('battleAnalysis').textContent);if(battle.evalBlack===null)document.getElementById('evalText').textContent=en?`Click the button to evaluate with KataGo; red represents Black's win rate.`:`点击按钮后由 KataGo 评估；红色代表黑方胜率。`;document.getElementById('evalText').textContent=translateMessage(document.getElementById('evalText').textContent);}
      if(typeof record!=='undefined'&&record){document.getElementById('recordName').textContent=record.meta?.title||document.getElementById('recordTitle').value||pick('未命名棋谱','Untitled record');document.getElementById('recordState').textContent=record.moveList.length?`${record.cursor} / ${record.moveList.length} ${en?'moves':'手'}`:pick('新棋谱','New record');document.getElementById('recordTurn').textContent=record.recordMode==='setupB'?pick('摆黑子','Place black stones'):record.recordMode==='setupW'?pick('摆白子','Place white stones'):en?`${record.cursor} / ${record.moveList.length} moves · ${record.turn==='B'?'Black':'White'} to play`:`${record.cursor} / ${record.moveList.length} 手 · ${record.turn==='B'?'黑方':'白方'}落子`;document.getElementById('recordAnalyze').textContent=record.insightVisible?pick('隐藏形势判断','Hide evaluation'):`${pick('形势判断','Evaluate position')} · ${ANALYSIS_VISITS} ${en?'visits':'次'}`;document.getElementById('recordAnalysis').textContent=record.evalBlack===null?pick('可以读取 SGF、GIB、NGF、JSON 或文本棋谱；腾讯围棋、野狐围棋导出的 SGF 可直接使用。','SGF, GIB, NGF, JSON, and text records are supported, including Tencent Go and Fox Go exports.'):en?`Black win rate is approximately ${(record.evalBlack*100).toFixed(1)}%.`:`当前局面黑方胜率约 ${(record.evalBlack*100).toFixed(1)}%。`;}
      if(document.getElementById('analysisDepthValue'))document.getElementById('analysisDepthValue').textContent=`${ANALYSIS_VISITS} ${en?'visits':'次'}`;
    }catch{}
  }
  function translateMessage(value){if(!value)return value;const pairs=[['自由推演：黑白交替落子。','Free review: Black and White alternate moves.'],['已退一步，可重新分析。','Undone one move; you can analyze again.'],['已落子，可继续推演。','Move played; continue reviewing.'],['已停一手','Passed once'],['连续停一手。点击棋块标记或取消死子，再确认结算。','Both sides passed. Click stones to mark or unmark dead groups, then confirm scoring.'],['轮到你落子','Your turn'],['等待 AI 落子','Waiting for AI'],['KataGo 尚未就绪，请确认本地服务已启动。','KataGo is not ready. Please confirm that the local service has started.'],['请先开始一局。','Start a game first.'],['AI 分析供参考，不等同于题库答案。','AI analysis is for reference and is not the source answer.'],['点击按钮后由 KataGo 评估；红色代表黑方胜率。','Click the button to evaluate with KataGo; red represents Black\'s win rate.'],['AI 未落子：','AI did not play: '],['。可重试或悔棋。','. Retry or undo.']];if(lang==='en')for(const [zh,en] of pairs)value=value.replaceAll(zh,en);else for(const [zh,en] of pairs)value=value.replaceAll(en,zh);return value.replace(lang==='en'?/已以 (\d+) 次深度显示当前局面的形势与前三推荐。/g:/Evaluation and the top three recommendations are shown after (\d+) visits\./g,lang==='en'?'Evaluation and the top three recommendations are shown after $1 visits。':'已以 $1 次深度显示当前局面的形势与前三推荐。');}
  function applyExtraDynamic(){const en=lang==='en';try{const feedbackIds=['puzzleFeedback','battleFeedback','recordFeedback'];for(const id of feedbackIds){const el=document.getElementById(id);if(el)el.textContent=translateMessage(el.textContent);}document.querySelectorAll('.rec-row small').forEach(el=>{el.textContent=en?el.textContent.replace('次',' visits'):el.textContent.replace(' visits','次');});if(typeof AI_LEVELS!=='undefined'){const id=document.getElementById('aiLevel')?.value||'amateur',hints={beginner:['入门 · 人类20级 · 1 次访问，最宽的落子分布','Starter · Human 20k · 1 visit; the widest human-like move distribution'],human10k:['入门 · 人类10级 · 2 次访问，保留明显的人类落子倾向','Starter · Human 10k · 2 visits; clearly human-like move choices'],veteran:['老手 · 人类5级 · 4 次访问，稳健但仍会犯错','Experienced · Human 5k · 4 visits; steady but still fallible'],amateur:['业余高手 · 人类1段 · 16 次访问，业余强手棋风','Strong amateur · Human 1d · 16 visits; strong amateur style'],amateur5d:['业余顶尖 · 人类5段 · 32 次访问，接近高段业余棋力','Top amateur · Human 5d · 32 visits; near top amateur strength'],pro:['职业棋手 · 职业九段 · 64 次访问，接近职业的选择','Professional · Pro 9d · 64 visits; near professional choices'],ai:['KataGo · 256 次访问，每次选择一选','KataGo · 256 visits; always chooses the top move']}[id];if(hints)document.getElementById('aiLevelHint').textContent=pick(...hints);}if(typeof engineReady!=='undefined'){const status=document.getElementById('engineStatus');if(status)status.textContent=engineReady?pick('KataGo · CPU 已就绪','KataGo · CPU ready'):pick('离线研习 · 对弈请启动本地服务','Offline study · start the local service for AI play');}const pa=document.getElementById('puzzleAnalysis');if(pa)pa.textContent=translateMessage(pa.textContent);const ba=document.getElementById('battleAnalysis');if(ba)ba.textContent=translateMessage(ba.textContent);const ra=document.getElementById('recordAnalysis');if(ra&&typeof record!=='undefined'&&record?.evalBlack===null)ra.textContent=pick('可以读取 SGF、GIB、NGF、JSON 或文本棋谱；腾讯围棋、野狐围棋导出的 SGF 可直接使用。','SGF, GIB, NGF, JSON, and text records are supported, including Tencent Go and Fox Go exports.');}catch{}}
  function applyBookLanguage(){try{const book=document.getElementById('bookName');if(book&&typeof current!=='undefined'&&current)book.textContent=pick('Go Game Guru Weekly Problems · An Younggil 8段、David Ormerod','Go Game Guru Weekly Problems · An Younggil 8d, David Ormerod');}catch{}}
  function apply(){applyStatic();applyDynamic();applyExtraDynamic();applyBookLanguage();}
  function hook(name){const original=window[name];if(typeof original!=='function'||original.__yijingI18n)return;const wrapped=function(...args){const result=original.apply(this,args);if(result&&typeof result.finally==='function')return result.finally(()=>{applyDynamic();applyExtraDynamic();applyBookLanguage();});applyDynamic();applyExtraDynamic();applyBookLanguage();return result;};wrapped.__yijingI18n=true;window[name]=wrapped;}
  ['progress','renderList','renderPuzzle','renderBattle','renderRecord','renderRecommendations','refreshAiLevelHint','switchPage','loadPuzzle','puzzleMove','demoSolution','battleMove','aiMove','battleRecommend','newRecord','loadParsedRecord','navigateRecord','recordBoardClick','analyzeRecord','readRecordFile','loadSavedRecord','refreshRecords','startBattle'].forEach(hook);
  document.addEventListener('DOMContentLoaded',apply,{once:true});
  const button=document.getElementById('languageToggle');if(button)button.onclick=()=>{lang=lang==='en'?'zh':'en';try{localStorage.setItem(KEY,lang);}catch{}apply();};
  apply();
})();
