const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Go=require('./go.js'),{validate}=require('./server.cjs');
test('capture, suicide, occupied points and positional superko',()=>{
  const b=Go.empty(9);b[1][1]='W';for(const [x,y] of [[0,1],[1,0],[2,1]])b[y][x]='B';const r=Go.play(b,'B',1,2);assert.equal(r.captured,1);assert.equal(r.board[1][1],null);assert.equal(b[1][1],'W');assert.throws(()=>Go.play(r.board,'W',1,1),/无气/);assert.throws(()=>Go.play(b,'W',1,1),/已有/);assert.throws(()=>Go.play(b,'B',1,2,[Go.key(r.board)]),/重复/);
  const ko=Go.empty(9);for(const [x,y] of [[1,2],[3,2],[2,3]])ko[y][x]='B';for(const [x,y] of [[2,2],[1,1],[3,1],[2,0]])ko[y][x]='W';const captured=Go.play(ko,'B',2,1);assert.equal(captured.captured,1);assert.throws(()=>Go.play(captured.board,'W',2,2,[Go.key(ko)]),/重复/);
});
test('pass, coordinates and area scoring',()=>{for(const n of [9,13,19])for(let x=0;x<n;x++)for(let y=0;y<n;y++)assert.deepEqual(Go.fromGtp(Go.toGtp(x,y,n),n),[x,y]);assert.deepEqual(Go.fromGtp('pass'),[null,null]);assert.throws(()=>Go.fromGtp('I4'));const b=Go.empty(9);b[0][0]='B';assert.equal(Go.area(b).B,81);assert.deepEqual(Go.play(b,'W',null,null).board,b);});
test('420 standard-solution problems have legal Correct paths',()=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/solutions.js','utf8'),ctx);const ps=ctx.window.SOLUTION_PUZZLES;assert.equal(ps.length,420);for(const level of ['easy','intermediate','hard'])assert.equal(ps.filter(p=>p.chapter===level).length,140);for(const p of ps){assert.ok(p.answerPaths.length,p.id);for(const line of p.answerPaths){let board=Go.empty(19),turn=p.player,history=[];for(const [c,x,y] of p.stones)board[y][x]=c;history=[Go.key(board)];for(const [color,x,y] of line){assert.equal(color,turn,p.id+' wrong player');const next=Go.play(board,color,x,y,history);board=next.board;history.push(Go.key(board));turn=Go.other(turn);}}}});
test('server rejects invalid turns, visits, board sizes and duplicate setup',()=>{const q={size:9,moves:[],initialPlayer:'B',visits:8};assert.throws(()=>validate({...q,moves:[['W','D4']]}));assert.throws(()=>validate({...q,visits:99999}));assert.throws(()=>validate({...q,analysisPVLen:0}));assert.equal(validate({...q,visits:64,analysisPVLen:20}).analysisPVLen,20);assert.throws(()=>validate({...q,size:50}));assert.throws(()=>validate({...q,initialStones:[['B','D4'],['W','D4']]}));for(const profile of ['rank_20k','rank_10k','rank_5k','rank_1d','rank_5d','rank_9d']){const human=validate({...q,visits:1,humanProfile:profile});assert.equal(human.maxVisits,1);assert.equal(human.includePolicy,true);assert.equal(human.overrideSettings.humanSLProfile,profile);}assert.throws(()=>validate({...q,humanProfile:'rank_99k'}));});
test('record parser reads SGF, GIB and NGF moves',()=>{const src=fs.readFileSync(__dirname+'/app.js','utf8'),start=src.indexOf('function sgfPoint'),end=src.indexOf('function collectInitial'),api=new Function('Go',src.slice(start,end)+';return {parseSgf};')(Go);const sgf=api.parseSgf('(;SZ[9]PB[黑]PW[白]AB[dd];B[ee];W[fd])','game.sgf');assert.equal(sgf.n,9);assert.deepEqual(sgf.initial,[['B',3,3]]);assert.deepEqual(sgf.moves,[['B','E5'],['W','F6']]);const savedSgf=api.parseSgf('(;SZ[19];B[pm];W[dd])','saved.sgf');assert.deepEqual(savedSgf.moves,[['B','Q7'],['W','D16']]);const gib=api.parseSgf('\\[GAMEBLACKNAME=黑\\]\n\\[GAMEWHITENAME=白\\]\nSTO 0 0 1 3 3\nSTO 0 1 2 4 4','game.gib');assert.deepEqual(gib.moves,[['B','D16'],['W','E15']]);const ngf=api.parseSgf('NGF\n19\n白\n黑\n0\n0\n0\n7.5\n20260906\n\nWhite win\nPM  Bdd\nPM  Wef','game.ngf');assert.deepEqual(ngf.moves,[['B','C17'],['W','D15']]);});
test('live KataGo legal responses and real search budgets',{skip:!process.env.LIVE_TEST,timeout:120000},async()=>{
 for(const visits of [8,32]){const q={size:9,initialPlayer:'B',moves:[['B','D4']],visits};const r=await fetch('http://127.0.0.1:8787/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(q)});const d=await r.json();assert.equal(r.status,200,JSON.stringify(d));assert.ok(d.rootInfo.visits>=visits);const m=d.moveInfos.find(m=>m.order===0);let b=Go.play(Go.empty(9),'B',3,5).board;assert.doesNotThrow(()=>Go.play(b,'W',...Go.fromGtp(m.move,9)));console.log('KataGo:',visits,'visits →',m.move,'actual',d.rootInfo.visits);}
});
